# Generated by Django 4.2.7 on 2025-11-17 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Role code like 'TENANT_ADMIN', 'EMPLOYEE'", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name like 'Tenant Administrator'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_management_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_slug', models.CharField(help_text='References tenant from tenant_management', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Invitation'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('invited_at', models.DateTimeField(blank=True, help_text='When invitation was sent', null=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When user accepted invitation')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last time user accessed this tenant')),
                ('is_active', models.BooleanField(default=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='user_management.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_management_tenantmembership',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['user', 'tenant_slug'], name='user_manage_user_id_ba0ce5_idx'), models.Index(fields=['tenant_slug', 'status'], name='user_manage_tenant__37df43_idx')],
                'unique_together': {('user', 'tenant_slug')},
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address to invite', max_length=254)),
                ('tenant_slug', models.CharField(help_text='Which tenant to join', max_length=50)),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Unique token for invitation link', unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(help_text='When invitation expires')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role to assign upon acceptance', on_delete=django.db.models.deletion.PROTECT, to='user_management.role')),
            ],
            options={
                'db_table': 'user_management_tenantinvitation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'tenant_slug', 'status'], name='user_manage_email_91968a_idx'), models.Index(fields=['token'], name='user_manage_token_915fcf_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_code', models.CharField(help_text="Permission code like 'assign_controls', 'manage_users'", max_length=100)),
                ('permission_name', models.CharField(help_text="Display name like 'Can assign controls to users'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='What this permission allows')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='user_management.role')),
            ],
            options={
                'db_table': 'user_management_rolepermission',
                'ordering': ['role', 'permission_code'],
                'unique_together': {('role', 'permission_code')},
            },
        ),
    ]
