# Generated by Django 4.2.7 on 2025-11-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission_code',
            field=models.CharField(choices=[('view_frameworks', 'Can view frameworks'), ('view_evidence', 'Can view evidence'), ('manage_users', 'Manage Users'), ('assign_controls', 'Assign Controls'), ('create_campaigns', 'Create Campaigns'), ('submit_responses', 'Submit Assessment Responses'), ('upload_evidence', 'Upload Evidence Documents'), ('generate_reports', 'Generate Compliance Reports'), ('view_reports', 'View Compliance Reports')], help_text="Permission code like 'assign_controls', 'manage_users'", max_length=100),
        ),
    ]
