# Generated by Django 4.2.7 on 2025-11-17 08:19

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Short code like 'AC', 'CM'", max_length=10)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['domain', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('control_code', models.CharField(help_text="Control code like 'AC-001'", max_length=20, validators=[django.core.validators.RegexValidator(message='Control code must be like AC-001, CM-001', regex='^[A-Z]{2,4}-\\d{3}$')])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objective', models.TextField(help_text='What this control aims to achieve')),
                ('control_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('DETECTIVE', 'Detective'), ('CORRECTIVE', 'Corrective')], default='PREVENTIVE', max_length=20)),
                ('frequency', models.CharField(choices=[('CONTINUOUS', 'Continuous'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=20)),
                ('risk_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'controls',
                'ordering': ['subcategory', 'sort_order', 'control_code'],
            },
        ),
        migrations.CreateModel(
            name='ControlTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="Tag name like 'cloud', 'automated', 'high-priority'", max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical'), ('OPERATIONAL', 'Operational'), ('STRATEGIC', 'Strategic'), ('DEPLOYMENT', 'Deployment'), ('PRIORITY', 'Priority')], default='TECHNICAL', max_length=20)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color code for UI badge', max_length=7)),
            ],
            options={
                'db_table': 'control_tags',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="Category name like 'Financial Compliance', 'Information Security'", max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(help_text="Short code like 'FIN', 'SEC', 'PRIV'", max_length=20, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Icon name for UI (e.g., 'shield', 'lock', 'document')", max_length=50)),
                ('color', models.CharField(default='#0066CC', help_text='Hex color code for UI', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Framework Categories',
                'db_table': 'framework_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Short code like 'UAM', 'SAM'", max_length=10)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='templates_host.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
                'db_table': 'subcategories',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImplementationGuidance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Detailed implementation instructions')),
                ('guidance_type', models.CharField(choices=[('TECHNICAL', 'Technical Implementation'), ('PROCEDURAL', 'Procedural Steps'), ('POLICY', 'Policy Template'), ('EXAMPLE', 'Example/Template')], default='TECHNICAL', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='INTERMEDIATE', max_length=20)),
                ('estimated_hours', models.PositiveIntegerField(blank=True, help_text='Estimated implementation time in hours', null=True)),
                ('prerequisites', models.TextField(blank=True, help_text='What needs to be in place before starting')),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementation_guides', to='templates_host.control')),
            ],
            options={
                'verbose_name_plural': 'Implementation Guidance',
                'db_table': 'implementation_guidance',
                'ordering': ['control', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="Short name like 'SOX', 'ISO27001'", max_length=50)),
                ('full_name', models.CharField(help_text="Full name like 'Sarbanes-Oxley Act'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', help_text="Version like '2024.1', '2022.1'", max_length=20)),
                ('effective_date', models.DateField(default=datetime.date.today, help_text='When this framework version becomes effective')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('applicable_industries', models.JSONField(blank=True, default=list, help_text="Industries this applies to - ['Finance', 'Healthcare', 'Technology']")),
                ('applicable_regions', models.JSONField(blank=True, default=list, help_text="Regions this applies to - ['US', 'EU', 'Global', 'APAC']")),
                ('compliance_authority', models.CharField(blank=True, help_text="Governing body (e.g., 'SEC', 'ISO', 'GDPR Authority', 'HIPAA')", max_length=100)),
                ('is_current_version', models.BooleanField(default=True, help_text='Is this the latest/current version of the framework?')),
                ('changelog', models.TextField(blank=True, help_text='What changed in this version compared to previous')),
                ('category', models.ForeignKey(blank=True, help_text='Category (Financial, Security, Privacy, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frameworks', to='templates_host.frameworkcategory')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='If deprecated, which version replaced this?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='templates_host.framework')),
            ],
            options={
                'db_table': 'frameworks',
                'ordering': ['name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('SCREENSHOT', 'Screenshot'), ('VIDEO', 'Video'), ('LOG_FILE', 'Log File'), ('REPORT', 'Report'), ('POLICY', 'Policy'), ('PROCEDURE', 'Procedure')], default='DOCUMENT', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('file_format', models.CharField(blank=True, help_text="Accepted file formats like 'PDF, DOC, XLSX'", max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_requirements', to='templates_host.control')),
            ],
            options={
                'db_table': 'evidence_requirements',
                'ordering': ['control', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text="Short code like 'ITGC', 'BPC'", max_length=10)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='templates_host.framework')),
            ],
            options={
                'db_table': 'domains',
                'ordering': ['framework', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ControlReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('reference_type', models.CharField(choices=[('REGULATION', 'Regulation'), ('STANDARD', 'Standard'), ('GUIDELINE', 'Guideline'), ('BEST_PRACTICE', 'Best Practice'), ('DOCUMENTATION', 'Documentation')], default='STANDARD', max_length=20)),
                ('reference_code', models.CharField(help_text="Reference identifier (e.g., 'SOX Section 404', 'NIST SP 800-53')", max_length=100)),
                ('reference_title', models.CharField(max_length=200)),
                ('reference_url', models.URLField(blank=True, help_text='Link to external documentation')),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='templates_host.control')),
            ],
            options={
                'db_table': 'control_references',
                'ordering': ['control', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ControlMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('mapping_type', models.CharField(choices=[('EQUIVALENT', 'Equivalent - Same requirement'), ('PARTIAL', 'Partial - Overlapping requirements'), ('RELATED', 'Related - Similar concept'), ('SUPERSEDES', 'Supersedes - Replaces older control')], default='EQUIVALENT', max_length=20)),
                ('mapping_strength', models.PositiveIntegerField(default=100, help_text='Strength of mapping (0-100%). 100% = fully equivalent')),
                ('notes', models.TextField(blank=True, help_text='Explanation of relationship between controls')),
                ('source_control', models.ForeignKey(help_text='Primary control', on_delete=django.db.models.deletion.CASCADE, related_name='mappings_as_source', to='templates_host.control')),
                ('target_control', models.ForeignKey(help_text='Related/equivalent control', on_delete=django.db.models.deletion.CASCADE, related_name='mappings_as_target', to='templates_host.control')),
            ],
            options={
                'db_table': 'control_mappings',
                'ordering': ['-mapping_strength', 'source_control'],
            },
        ),
        migrations.CreateModel(
            name='ControlDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('dependency_type', models.CharField(choices=[('REQUIRED', 'Required - Must implement first'), ('RECOMMENDED', 'Recommended - Should implement first'), ('OPTIONAL', 'Optional - Helpful to implement first')], default='REQUIRED', max_length=20)),
                ('description', models.TextField(help_text='Why this dependency exists')),
                ('control', models.ForeignKey(help_text='Control that has the dependency', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='templates_host.control')),
                ('depends_on_control', models.ForeignKey(help_text='Control that must be implemented first', on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='templates_host.control')),
            ],
            options={
                'verbose_name_plural': 'Control Dependencies',
                'db_table': 'control_dependencies',
            },
        ),
        migrations.AddField(
            model_name='control',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls', to='templates_host.subcategory'),
        ),
        migrations.AddField(
            model_name='control',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for categorization and filtering (cloud, automated, high-priority)', related_name='controls', to='templates_host.controltag'),
        ),
        migrations.AddField(
            model_name='category',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='templates_host.domain'),
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('YES_NO', 'Yes/No'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('TEXT', 'Text Response'), ('NUMERIC', 'Numeric'), ('DATE', 'Date')], default='YES_NO', max_length=20)),
                ('options', models.JSONField(blank=True, help_text='For multiple choice questions - list of options', null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='templates_host.control')),
            ],
            options={
                'db_table': 'assessment_questions',
                'ordering': ['control', 'sort_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'code'), name='unique_subcategory_code_per_category'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'name'), name='unique_subcategory_name_per_category'),
        ),
        migrations.AddConstraint(
            model_name='framework',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_framework_name_version'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('framework__isnull', False)), fields=('framework', 'code'), name='unique_domain_code_per_framework'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('framework__isnull', False)), fields=('framework', 'name'), name='unique_domain_name_per_framework'),
        ),
        migrations.AlterUniqueTogether(
            name='controlmapping',
            unique_together={('source_control', 'target_control')},
        ),
        migrations.AlterUniqueTogether(
            name='controldependency',
            unique_together={('control', 'depends_on_control')},
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(condition=models.Q(('subcategory__isnull', False)), fields=('subcategory', 'control_code'), name='unique_control_code_per_subcategory'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('domain__isnull', False)), fields=('domain', 'code'), name='unique_category_code_per_domain'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('domain__isnull', False)), fields=('domain', 'name'), name='unique_category_name_per_domain'),
        ),
    ]
