# Generated by Django 4.2.7 on 2025-11-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates_host', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='templates_host.subcategory'),
            preserve_default=False,
        ),
    ]
