# Generated by Django 4.2.7 on 2025-11-17 08:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(help_text="Plan code like 'BASIC', 'PROFESSIONAL', 'ENTERPRISE'", max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Price in USD per month', max_digits=10)),
                ('annual_price', models.DecimalField(decimal_places=2, help_text='Price in USD per year (discounted)', max_digits=10)),
                ('max_users', models.IntegerField(default=0, help_text='Maximum number of users (0 = unlimited)')),
                ('max_frameworks', models.IntegerField(default=0, help_text='Maximum number of frameworks (0 = unlimited)')),
                ('max_controls', models.IntegerField(default=0, help_text='Maximum number of controls (0 = unlimited)')),
                ('storage_gb', models.IntegerField(default=10, help_text='Storage limit in GB')),
                ('can_create_custom_frameworks', models.BooleanField(default=False, help_text='Can create custom frameworks from scratch')),
                ('can_customize_controls', models.BooleanField(default=True, help_text='Can customize individual control descriptions')),
                ('has_api_access', models.BooleanField(default=False, help_text='Has API access for integrations')),
                ('has_advanced_reporting', models.BooleanField(default=False, help_text='Advanced compliance reporting features')),
                ('has_sso', models.BooleanField(default=False, help_text='Single Sign-On (SSO) support')),
                ('default_isolation_mode', models.CharField(choices=[('SCHEMA', 'Schema-based (shared database)'), ('DATABASE', 'Database-based (dedicated)')], default='SCHEMA', help_text='Default database isolation strategy for this plan', max_length=20)),
                ('default_customization_level', models.CharField(choices=[('VIEW_ONLY', 'View Only - No customization'), ('CONTROL_LEVEL', 'Control Level - Customize controls'), ('FULL', 'Full - Complete customization')], default='VIEW_ONLY', help_text='Default framework customization level', max_length=20)),
                ('support_level', models.CharField(choices=[('EMAIL', 'Email Support'), ('PRIORITY', 'Priority Support'), ('DEDICATED', 'Dedicated Account Manager')], default='EMAIL', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='TenantDatabaseInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant_slug', models.SlugField(help_text="Unique identifier like 'acmecorp', 'techstartup'", unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase letters, numbers, and hyphens only', regex='^[a-z0-9-]+$')])),
                ('company_name', models.CharField(help_text='Full company name', max_length=200)),
                ('company_email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('company_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('database_name', models.CharField(help_text='PostgreSQL database name (if DATABASE mode)', max_length=100)),
                ('database_user', models.CharField(blank=True, help_text='Database user (if DATABASE mode)', max_length=50)),
                ('database_password', models.TextField(help_text='Encrypted password (Fernet encryption)')),
                ('database_host', models.CharField(default='localhost', help_text='Database host address', max_length=100)),
                ('database_port', models.CharField(default='5432', help_text='Database port', max_length=10)),
                ('isolation_mode', models.CharField(choices=[('DATABASE', 'Separate Database'), ('SCHEMA', 'Schema in Shared Database')], default='SCHEMA', help_text='Database isolation strategy', max_length=20)),
                ('schema_name', models.CharField(blank=True, help_text="Schema name if SCHEMA mode (e.g., 'acmecorp_schema')", max_length=100)),
                ('subscription_status', models.CharField(choices=[('TRIAL', 'Trial Period'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=20)),
                ('subscription_start_date', models.DateField(help_text='When subscription started')),
                ('subscription_end_date', models.DateField(blank=True, help_text='When subscription ends (null = ongoing)', null=True)),
                ('trial_end_date', models.DateField(blank=True, help_text='When trial period ends', null=True)),
                ('current_user_count', models.IntegerField(default=0, help_text='Current number of active users')),
                ('current_framework_count', models.IntegerField(default=0, help_text='Current number of subscribed frameworks')),
                ('current_control_count', models.IntegerField(default=0, help_text='Current number of controls')),
                ('storage_used_gb', models.DecimalField(decimal_places=2, default=0, help_text='Storage used in GB', max_digits=10)),
                ('provisioning_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROVISIONING', 'Provisioning'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('DEPROVISIONING', 'Deprovisioning')], default='PENDING', max_length=20)),
                ('provisioning_error', models.TextField(blank=True, help_text='Error message if provisioning failed')),
                ('user_data_residency', models.CharField(choices=[('CENTRALIZED', 'Centralized (Main DB)'), ('ISOLATED', 'Isolated (Tenant DB)')], default='CENTRALIZED', help_text='Where user data is stored', max_length=20)),
                ('provisioned_at', models.DateTimeField(blank=True, help_text='When provisioning completed', null=True)),
                ('last_health_check', models.DateTimeField(blank=True, help_text='Last time system checked tenant health', null=True)),
                ('subscription_plan', models.ForeignKey(help_text='Current subscription plan', on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenant_management.subscriptionplan')),
            ],
            options={
                'db_table': 'tenant_database_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantBillingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_period_start', models.DateField(help_text='Billing period start date')),
                ('billing_period_end', models.DateField(help_text='Billing period end date')),
                ('base_plan_amount', models.DecimalField(decimal_places=2, help_text='Base subscription plan amount', max_digits=10)),
                ('addon_frameworks_amount', models.DecimalField(decimal_places=2, default=0, help_text='Additional framework charges', max_digits=10)),
                ('addon_users_amount', models.DecimalField(decimal_places=2, default=0, help_text='Additional user charges', max_digits=10)),
                ('addon_storage_amount', models.DecimalField(decimal_places=2, default=0, help_text='Additional storage charges', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for this period', max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, help_text='When payment was received', null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used (credit card, bank transfer, etc.)', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100)),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=50, unique=True)),
                ('invoice_url', models.URLField(blank=True, help_text='Link to download invoice PDF')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_history', to='tenant_management.tenantdatabaseinfo')),
            ],
            options={
                'db_table': 'tenant_billing_history',
                'ordering': ['-billing_period_start'],
            },
        ),
        migrations.CreateModel(
            name='SuperAdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_user_id', models.IntegerField(help_text='User ID of the admin who performed action')),
                ('admin_username', models.CharField(help_text='Username for quick reference', max_length=150)),
                ('action', models.CharField(choices=[('VIEW_CREDENTIALS', 'Viewed database credentials'), ('IMPERSONATE', 'Impersonated tenant admin'), ('QUERY_DATABASE', 'Ran database query'), ('CREATE_TENANT', 'Created new tenant'), ('DELETE_TENANT', 'Deleted tenant'), ('SUSPEND_TENANT', 'Suspended tenant'), ('MODIFY_SUBSCRIPTION', 'Modified subscription'), ('VIEW_TENANT_DATA', 'Viewed tenant data')], help_text='Action performed by admin', max_length=50)),
                ('tenant_slug', models.CharField(blank=True, help_text='Which tenant was affected', max_length=50)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of admin')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
                ('reason', models.TextField(blank=True, help_text='Reason for performing this action')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When action was performed')),
            ],
            options={
                'db_table': 'superadmin_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['admin_user_id', 'timestamp'], name='superadmin__admin_u_71ea8a_idx'), models.Index(fields=['tenant_slug', 'timestamp'], name='superadmin__tenant__af3f6b_idx'), models.Index(fields=['action', 'timestamp'], name='superadmin__action_463969_idx')],
            },
        ),
        migrations.CreateModel(
            name='FrameworkSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('framework_id', models.UUIDField(help_text='ID of Framework from templates_host app')),
                ('framework_name', models.CharField(help_text='Cached framework name for quick access', max_length=200)),
                ('framework_version', models.CharField(help_text="Version subscribed to (e.g., '1.0')", max_length=20)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When framework was subscribed')),
                ('subscription_type', models.CharField(choices=[('INCLUDED', 'Included in plan'), ('ADDON', 'Add-on purchase')], default='INCLUDED', max_length=20)),
                ('addon_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price if add-on (monthly)', max_digits=10, null=True)),
                ('customization_level', models.CharField(choices=[('VIEW_ONLY', 'View Only - No copy'), ('CONTROL_LEVEL', 'Control Level - Full copy, can customize controls'), ('FULL', 'Full - Independent copy, full customization')], default='CONTROL_LEVEL', help_text='Level of customization allowed', max_length=20)),
                ('current_version', models.CharField(help_text='Version currently deployed in tenant schema', max_length=20)),
                ('latest_available_version', models.CharField(help_text='Latest version available from template', max_length=20)),
                ('upgrade_status', models.CharField(choices=[('UP_TO_DATE', 'Up to date'), ('UPGRADE_AVAILABLE', 'Upgrade available'), ('UPGRADE_SCHEDULED', 'Upgrade scheduled'), ('UPGRADING', 'Upgrading'), ('UPGRADE_FAILED', 'Upgrade failed')], default='UP_TO_DATE', max_length=20)),
                ('last_upgrade_check', models.DateTimeField(blank=True, help_text='Last time system checked for updates', null=True)),
                ('scheduled_upgrade_date', models.DateTimeField(blank=True, help_text='When upgrade is scheduled', null=True)),
                ('has_customizations', models.BooleanField(default=False, help_text='Has tenant customized any controls?')),
                ('customized_controls_count', models.IntegerField(default=0, help_text='Number of customized controls')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When subscription was cancelled', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_subscriptions', to='tenant_management.tenantdatabaseinfo')),
            ],
            options={
                'db_table': 'framework_subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('log_date', models.DateField(help_text='Date of this usage snapshot')),
                ('user_count', models.IntegerField(help_text='Number of active users')),
                ('framework_count', models.IntegerField(help_text='Number of subscribed frameworks')),
                ('control_count', models.IntegerField(help_text='Total number of controls')),
                ('assessment_count', models.IntegerField(default=0, help_text='Number of assessment campaigns')),
                ('evidence_count', models.IntegerField(default=0, help_text='Number of evidence documents')),
                ('storage_used_gb', models.DecimalField(decimal_places=2, help_text='Storage used in GB', max_digits=10)),
                ('api_calls_count', models.IntegerField(default=0, help_text='Number of API calls made')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='tenant_management.tenantdatabaseinfo')),
            ],
            options={
                'db_table': 'tenant_usage_logs',
                'ordering': ['-log_date'],
                'indexes': [models.Index(fields=['tenant', 'log_date'], name='tenant_usag_tenant__b0b642_idx')],
                'unique_together': {('tenant', 'log_date')},
            },
        ),
        migrations.AddIndex(
            model_name='tenantdatabaseinfo',
            index=models.Index(fields=['tenant_slug'], name='tenant_data_tenant__dd0b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdatabaseinfo',
            index=models.Index(fields=['provisioning_status'], name='tenant_data_provisi_34c02b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdatabaseinfo',
            index=models.Index(fields=['subscription_status'], name='tenant_data_subscri_d766cd_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbillinghistory',
            index=models.Index(fields=['tenant', 'payment_status'], name='tenant_bill_tenant__27e6e2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbillinghistory',
            index=models.Index(fields=['billing_period_start'], name='tenant_bill_billing_ead252_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbillinghistory',
            index=models.Index(fields=['invoice_number'], name='tenant_bill_invoice_122531_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworksubscription',
            index=models.Index(fields=['tenant', 'status'], name='framework_s_tenant__aad06a_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworksubscription',
            index=models.Index(fields=['upgrade_status'], name='framework_s_upgrade_dd183b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frameworksubscription',
            unique_together={('tenant', 'framework_id')},
        ),
    ]
