# Generated by Django 4.2.7 on 2025-11-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdatabaseinfo',
            name='subscription_start_date',
            field=models.DateField(blank=True, help_text='When subscription started', null=True),
        ),
    ]
