# Generated by Django 4.2.7 on 2025-11-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_make_subscription_dates_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='default_isolation_mode',
        ),
        migrations.RemoveField(
            model_name='tenantdatabaseinfo',
            name='isolation_mode',
        ),
        migrations.AlterField(
            model_name='tenantdatabaseinfo',
            name='database_host',
            field=models.CharField(default='localhost', help_text='Database host (main database)', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenantdatabaseinfo',
            name='database_name',
            field=models.CharField(default='main_compliance_system_db', help_text='Always uses main database (SCHEMA mode)', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenantdatabaseinfo',
            name='database_password',
            field=models.TextField(blank=True, help_text='Not used in SCHEMA mode (uses main DB credentials)'),
        ),
        migrations.AlterField(
            model_name='tenantdatabaseinfo',
            name='database_user',
            field=models.CharField(blank=True, help_text='Uses main database user', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenantdatabaseinfo',
            name='schema_name',
            field=models.CharField(help_text="Schema name (e.g., 'acmecorp_schema')", max_length=100),
        ),
    ]
