# Generated by Django 4.2.7 on 2025-11-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0003_remove_subscriptionplan_default_isolation_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdatabaseinfo',
            name='subscription_status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('DELETED', 'Deleted')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
