# Generated by Django 4.2.7 on 2025-11-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0004_alter_tenantdatabaseinfo_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantdatabaseinfo',
            name='trial_end_date',
        ),
    ]
