# Generated by Django 4.2.7 on 2025-12-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0005_remove_tenantdatabaseinfo_trial_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdatabaseinfo',
            name='requested_frameworks',
            field=models.JSONField(blank=True, default=list, help_text="Frameworks requested during tenant signup [{'id': 'uuid', 'name': 'SOX'}, ...]"),
        ),
    ]
