# Generated by Django 4.2.7 on 2025-11-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontrol',
            name='custom_description',
            field=models.TextField(blank=True, help_text="Company's custom description", null=True),
        ),
        migrations.AlterField(
            model_name='companycontrol',
            name='custom_objective',
            field=models.TextField(blank=True, help_text="Company's custom objective", null=True),
        ),
        migrations.AlterField(
            model_name='companycontrol',
            name='custom_procedures',
            field=models.TextField(blank=True, help_text='Company-specific implementation procedures', null=True),
        ),
        migrations.AlterField(
            model_name='companycontrol',
            name='custom_title',
            field=models.CharField(blank=True, help_text="Company's custom title", max_length=200, null=True),
        ),
    ]
