# Generated by Django 4.2.7 on 2025-11-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_compliance', '0002_make_custom_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresponse',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes added by approver'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When response was approved', null=True),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='approved_by_user_id',
            field=models.IntegerField(blank=True, help_text='User ID who approved this response', null=True),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='approved_by_username',
            field=models.CharField(blank=True, help_text='Username of approver (cached)', max_length=150),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When response was rejected', null=True),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='rejected_by_user_id',
            field=models.IntegerField(blank=True, help_text='User ID who rejected this response', null=True),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='rejected_by_username',
            field=models.CharField(blank=True, help_text='Username of rejector (cached)', max_length=150),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Specific feedback on why rejected'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='review_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUIRED', 'Revision Required')], default='DRAFT', help_text='Approval workflow status', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='revision_count',
            field=models.IntegerField(default=0, help_text='Number of times response was revised'),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes added by approver'),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When assignment was approved', null=True),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='approved_by_user_id',
            field=models.IntegerField(blank=True, help_text='User ID who approved this assignment', null=True),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='approved_by_username',
            field=models.CharField(blank=True, help_text='Username of approver (cached)', max_length=150),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When assignment was rejected', null=True),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='rejected_by_user_id',
            field=models.IntegerField(blank=True, help_text='User ID who rejected this assignment', null=True),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='rejected_by_username',
            field=models.CharField(blank=True, help_text='Username of rejector (cached)', max_length=150),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (required when rejecting)'),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='review_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUIRED', 'Revision Required')], default='NOT_SUBMITTED', help_text='Approval workflow status', max_length=20),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='revision_count',
            field=models.IntegerField(default=0, help_text='Number of times assignment was revised'),
        ),
        migrations.AddField(
            model_name='controlassignment',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, help_text='When assignment was submitted for review', null=True),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='previous_versions',
            field=models.JSONField(blank=True, default=list, help_text='History of previous rejected versions'),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When evidence was rejected', null=True),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='rejected_by_user_id',
            field=models.IntegerField(blank=True, help_text='User ID who rejected this evidence', null=True),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='rejected_by_username',
            field=models.CharField(blank=True, help_text='Username of rejector (cached)', max_length=150),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for evidence rejection'),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='resubmission_count',
            field=models.IntegerField(default=0, help_text='Number of times evidence was resubmitted'),
        ),
        migrations.AddField(
            model_name='evidencedocument',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('SUBMITTED', 'Submitted for Review'), ('UNDER_VERIFICATION', 'Under Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Verification workflow status', max_length=20),
        ),
    ]
